@startuml
!include style.puml
skinparam nodesep 50
skinparam ranksep 50

node "User's Computer" <<device>> as UserPC {
    node "OS (Windows / macOS / Linux)" <<executionEnvironment>> as OS {
        node "Java 21 Runtime" <<executionEnvironment>> as JRE {
            artifact "FairShare.jar" as App
        }
    }
}

file "data/expenses.txt" as StorageFile

App -right-> StorageFile : " Reads/Writes to local disk"
@enduml