@startuml
skinparam dpi 150
skinparam defaultFontSize 13
skinparam ClassFontSize 13
skinparam ClassAttributeFontSize 12
skinparam ArrowFontSize 12
skinparam ClassPadding 15
skinparam Nodesep 60
skinparam Ranksep 60
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

    package Parser <<Rectangle>> {
        Class FairShareParser
        Class AddCommandParser
        Class DeleteCommandParser
        Class UpdateCommandParser
        Class FilterCommandParser
        Class SettleCommandParser
    }

    package Commands <<Rectangle>> {
        Class "{abstract}\nCommand" as Command
        Class AddCommand
        Class DeleteCommand
        Class UpdateCommand
        Class FilterCommand
        Class ListCommand
        Class SettleCommand
        Class HelpCommand
        Class ExitCommand
    }

    Class CommandResult
    Class "<<interface>>\nLogic" as Logic
    Class LogicManager
}

package Model {
    Class HiddenModel #FFFFFF
}

package Storage {
    Class HiddenStorage #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic

LogicManager -right-> "1" FairShareParser

FairShareParser ..> AddCommandParser : <<create>>
FairShareParser ..> DeleteCommandParser : <<create>>
FairShareParser ..> UpdateCommandParser : <<create>>
FairShareParser ..> FilterCommandParser : <<create>>
FairShareParser ..> SettleCommandParser : <<create>>

AddCommandParser ..> AddCommand : <<create>>
DeleteCommandParser ..> DeleteCommand : <<create>>
UpdateCommandParser ..> UpdateCommand : <<create>>
FilterCommandParser ..> FilterCommand : <<create>>
SettleCommandParser ..> SettleCommand : <<create>>

AddCommand -up-|> Command
DeleteCommand -up-|> Command
UpdateCommand -up-|> Command
FilterCommand -up-|> Command
ListCommand -up-|> Command
SettleCommand -up-|> Command
HelpCommand -up-|> Command
ExitCommand -up-|> Command

LogicManager .left.> Command : <<executes>>

LogicManager --> Model
LogicManager --> Storage
Command .right.> Model

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : <<create>>

Storage --[hidden] Model
Command .[hidden]up.> Storage

@enduml
