@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_4
skinparam classBackgroundColor LOGIC_COLOR
skinparam nodesep 50
skinparam ranksep 50

package Logic as LogicPackage {

    Class "<<interface>>\nLogic" as Logic
    Class LogicManager

    package ParserPackage as "Parser" {
        Class FairShareParser
        Class "<<interface>>\nParser" as ParserInterface
        Class XYZCommandParser
        Class "<<utility>>\nParserUtil" as ParserUtil
    }

    package CommandsPackage as "Commands" {
        Class "{abstract}\nCommand" as Command
        Class XYZCommand
        Class CommandResult
    }
}

package Model <<Rectangle>> {
    Class HiddenModel #FFFFFF
}

package Storage <<Rectangle>> {
    Class HiddenStorage #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic

LogicManager -down-> "1" FairShareParser
LogicManager .down.> Command : <<executes>>

XYZCommandParser .up.|> ParserInterface
XYZCommandParser ..> ParserUtil

FairShareParser .down.> XYZCommandParser : <<create>>
FairShareParser .down.> XYZCommand : <<create>>

XYZCommandParser ..> XYZCommand : <<create>>

XYZCommand -up-|> Command

LogicManager .down.> CommandResult
Logic .down.> CommandResult
Command .up.> CommandResult : <<create>>

LogicManager -right-> Model
LogicManager -right-> Storage
Command .right.> Model

ParserPackage -[hidden]right- CommandsPackage
Model -[hidden]down- Storage
@enduml