@startuml
!include style.puml
skinparam linetype ortho
skinparam ArrowThickness 1.5
skinparam ArrowColor STORAGE_COLOR_4
skinparam classBackgroundColor STORAGE_COLOR
skinparam nodesep 60
skinparam ranksep 60

package Storage as StoragePackage <<Rectangle>> {
    interface FairShareStorage
    interface Storage

    class StorageManager
    class TxtFairShareStorage
    class TxtSerializableFairShare
    class TxtAdaptedExpense
    class TxtAdaptedGroup
    class TxtAdaptedPerson
    class TxtAdaptedParticipant
    class TxtAdaptedTag

    Storage ..|> FairShareStorage
    StorageManager ..|> Storage
    StorageManager --> FairShareStorage

    TxtFairShareStorage ..|> FairShareStorage
    TxtFairShareStorage ..> TxtSerializableFairShare : load/save

    TxtSerializableFairShare *-- "*" TxtAdaptedExpense
    TxtAdaptedExpense *-- "1" TxtAdaptedGroup : group
    TxtAdaptedExpense *-- "1" TxtAdaptedPerson : payer
    TxtAdaptedExpense *-- "*" TxtAdaptedParticipant : participants
    TxtAdaptedExpense *-- "*" TxtAdaptedTag : tags
    TxtAdaptedParticipant *-- "1" TxtAdaptedPerson : person
}

@enduml
