@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR
skinparam nodesep 60
skinparam ranksep 60

package Storage as StoragePackage {

    Class "<<interface>>\nStorage" as Storage
    Class StorageManager

    package "FairShare Storage" #F4F6F6 {
        Class "<<interface>>\nFairShareStorage" as FairShareStorage
        Class TxtFairShareStorage
        Class TxtSerializableFairShare
        Class TxtAdaptedExpense
        Class TxtAdaptedPerson
        Class TxtAdaptedTag
        Class TxtAdaptedParticipant
    }
}

Class HiddenOutside #FFFFFF
HiddenOutside -down..> Storage

StorageManager .up.|> Storage
Storage -right-|> FairShareStorage

StorageManager -down-> "1" FairShareStorage

TxtFairShareStorage .up.|> FairShareStorage

TxtFairShareStorage ..> TxtSerializableFairShare
TxtSerializableFairShare *-down-> "*" TxtAdaptedExpense
TxtAdaptedExpense *-down-> "1" TxtAdaptedPerson : payer >
TxtAdaptedExpense *-down-> "*" TxtAdaptedParticipant : participants >
TxtAdaptedExpense *-down-> "*" TxtAdaptedTag : tags >
TxtAdaptedParticipant *-down-> "1" TxtAdaptedPerson : person >

@enduml
