@startuml
!include style.puml
skinparam linetype ortho
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR_4
skinparam classBackgroundColor STORAGE_COLOR
skinparam nodesep 50
skinparam ranksep 50

Class HiddenOutside #FFFFFF

package Storage as StoragePackage <<Rectangle>> {
    interface "<<interface>>\nFairShareStorage" as FairShareStorage
    interface "<<interface>>\nStorage" as Storage

    class StorageManager
    class TxtFairShareStorage
    class TxtSerializableFairShare
    class TxtAdaptedExpense
    class TxtAdaptedGroup
    class TxtAdaptedPerson
    class TxtAdaptedParticipant
    class TxtAdaptedTag

    HiddenOutside .down.> Storage

    Storage -up-|> FairShareStorage

    StorageManager .up.|> Storage
    StorageManager -right-> "1" FairShareStorage

    TxtFairShareStorage .up.|> FairShareStorage
    TxtFairShareStorage .down.> TxtSerializableFairShare : load/save >

    TxtSerializableFairShare *-down-> "*" TxtAdaptedExpense

    TxtAdaptedExpense *-left-> "1" TxtAdaptedGroup : group
    TxtAdaptedExpense *-right-> "*" TxtAdaptedTag : tags
    TxtAdaptedExpense *-down-> "*" TxtAdaptedParticipant : participants
    TxtAdaptedExpense *-down-> "1" TxtAdaptedPerson : payer

    TxtAdaptedParticipant *-right-> "1" TxtAdaptedPerson : person
}

@enduml